apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: vault
spec:
  vault:
    path: pki/sign/cert-manager
    server: https://vault-pki.cert-manager.svc:8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBRENDQWVpZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREF4TVJNd0VRWURWUVFLRXdwamIzSmwKYjNNdVkyOXRNUm93R0FZRFZRUURFeEYyWVhWc2RDQnZjR1Z5WVhSdmNpQkRRVEFlRncweE9UQTJNREV4TURRdwpNekJhRncweU1EQTFNekV4TURRd016QmFNREV4RXpBUkJnTlZCQW9UQ21OdmNtVnZjeTVqYjIweEdqQVlCZ05WCkJBTVRFWFpoZFd4MElHOXdaWEpoZEc5eUlFTkJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUIKQ2dLQ0FRRUFyZHNXNFVMUENQeDd2OGxCd09ZU1d5cHhJbnVURGovWVFha3JFUm51VWdFRURLdUFQRlUrUzJnTwpvc2NrWmd5a2FnN1h0cks2QUVHSVY3TG1hdnlZTnpFMjNSRitBUGV5U1JHTkFXRE5RUjZrenk2bWNVc1gwN1JTCnNwdlkvczRFUUEycngvcWpIM2pRUGt4eVpHUEZ6Mm56VGgyb2ZLVHZvRkw1enZxMEJpZU1ZQUpyTGFrb01yQkIKL0Q4VXBkdHRYZ3pNRndXT1BETHdyMnNUOGYyZm9yRjdxZS8xVHhTd3RkL0lEVW40WHZFdkRhaGYvb3BSWGQ2TApvSVZMRTdPWXJ4eFcrNXFpbTYwUGpHdHlFays5b1I5NEEwQzQ0OTZ1emRCL29zVWZHUlFVdmxHN0FHMXZuM1FJCnUvd2Q1ejlpMk9vR3lPWjlneGl4bDVpS1I2ZkNLd0lEQVFBQm95TXdJVEFPQmdOVkhROEJBZjhFQkFNQ0FxUXcKRHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBQUVQamk3azRDajgyYWtuYgpON25uUjJabWZWSHRBYlNHQWllS0pkc3ZsSHFSeDFGMVhSWFdyOWxVa0NJbFNsVkl2ZjJ0U2psdWVZOFZWdEN4CmhCY2h3U2VHNXdZUGhBeG1LdzREejFVVkhhSXZRdjFTU3NNS2x4RE1mZm1mN2FqSTJwL1JkclY5WWpvQVlnaGMKc1J5NFg3cStGNDdybmFlUHBRaEpZcm9OSEloWEVEOUVhTW01SGR0WjVpWDduZC9pbmg2RjdVNW9UbzB2TmhWNAphSDJxRGlEaUFDOXlLdkNUTEgzaHkzUWx5aisrYjlpcEwxTVl1NGFvVThNUEN5b00vWXpwSjFsWDhVRWZKMHNVCnp5b3VpMDZ4UmN3c0ZUUnB5cjd6WVlHYUVpUzZqWklrazIybzJjWFZza09ubEJXeE5jdndmclgvbHRyS3B1LzIKaW5MeGNnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    auth:
      appRole:
        path: approle
        roleId: "9b3d31d1-5912-b575-31f6-5daec4168bed"
        secretRef:
          name: cert-manager-vault-approle
          key: secretId
