---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: kuard
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~v0.9.*
    flux.weave.works/locked: 'true'
    flux.weave.works/locked_msg: '"Halt updates for now"'
    flux.weave.works/locked_user: Smana <smainklh@gmail.com>
spec:
  releaseName: kuard
  chart:
    repository: https://github.com/Smana/gitops-flux-demo
    name: kuard
    path: flux/charts/kuard
    version: 0.0.1
  values:
    image:
      repository: gcr.io/kuar-demo/kuard-amd64
      tag: v0.9-purple
    service:
      type: LoadBalancer
