apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: smana-test
spec:
  secretName: smana-tls
  duration: 24h
  renewBefore: 6h
  issuerRef:
    name: vault
  commonName: myblog.smana.dev
  dnsNames:
  - myblog.smana.dev
  - www.myblog.smana.dev
