apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: flux-helm-client
spec:
  secretName: flux-helm-client-tls
  duration: 24h
  renewBefore: 6h
  issuerRef:
    name: vault-issuer
  commonName: flux-helm-client.smana.dev
  dnsNames:
  - flux-helm-client.smana.dev
