apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: flux-tiller
spec:
  secretName: flux-tiller-tls
  duration: 24h
  renewBefore: 6h
  issuerRef:
    name: vault-issuer
  commonName: tiller-deploy.smana.dev
  dnsNames:
  - tiller-deploy.smana.dev
