apiVersion: smana.dev/v1alpha1
kind: Flux
metadata:
  name: demo-kuard
spec:
  git:
    url: git@github.com:Smana/gitops-flux-demo
    branch: master
    path: "flux/demo-cluster"
    secretName: "demo-flux-ssh"
  helmOperator:
    allowNamespace: "demo"
    create: true
    createCRD: false
    tillerNamespace: flux
    tls:
      verify: true
      enable: true
      hostname: tiller-deploy.smana.dev
  additionalArgs:
  - --git-sync-tag=demo-cluster
  memcached:
    enabled: false
